steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package',
         '-Dmaven.test.skip=true',
         '-Drelease.tagName=$TAG_NAME',
         '-Drelease.shortSha=$SHORT_SHA',
         '-Drelease.repoName=spark-wordcount']
- name: 'ubuntu'
  args: ['sed',
         '-i',
         's@THE_LATEST_JAR@gs://macys-artifacts-test-1/$REPO_NAME/spark-wordcount-$TAG_NAME-$SHORT_SHA.jar@g',
         'wordcount-job-template.py']
- name: 'ubuntu'
  args: ['sed',
         '-i',
         's@DAG_ID@$SHORT_SHA@g',
         'wordcount-job-template.py']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp',
         'target/spark-wordcount-$TAG_NAME-$SHORT_SHA.jar',
         'gs://macys-artifacts-test-1/$REPO_NAME/']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp',
         'wordcount-job-template.py',
         'gs://us-central1-macys-test-env-be33d558-bucket/dags/']
