steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package',
         '-Dmaven.test.skip=true',
         '-Drelease.tagName=$TAG_NAME',
         '-Drelease.shortSha=$SHORT_SHA',
         '-Drelease.repoName=$REPO_NAME']
- name: 'ubuntu'
  args: ['sed',
         '-i',
         '"s@THE_LATEST_JAR@gs://macys-artifacts-test-1/$REPO_NAME/$REVISION_ID/$REPO_NAME-$TAG_NAME-$SHORT_SHA.jar@g"',
         'wordcount-job-template.py']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp',
         'target/$REPO_NAME-$TAG_NAME-$SHORT_SHA.jar',
         'gs://macys-artifacts-test-1/$REPO_NAME/$REVISION_ID']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp',
         'wordcount-job-template.py',
         'gs://us-central1-macys-test-env-be33d558-bucket/dags']
