steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package',
         '-Dmaven.test.skip=true',
         '-Drelease.tagName=$TAG_NAME',
         '-Drelease.shortSha=$SHORT_SHA',
         '-Drelease.repoName=spark-wordcount']
artifacts:
  objects:
    location: 'gs://macys-artifacts-test-1/$REPO_NAME/$REVISION_ID'
    paths: ['target/$REPO_NAME-$TAG_NAME-$SHORT_SHA.jar']
